### ISSUE TITLE
Add an image manager in k8s

### ISSUE THREAD

**Issue by darioamorosodaragona-tuni** [darioamorosodaragona-tuni/LogicalCouplingTool#5]
The automatic setup for the new images (keel) don't destroy the obsolete images. we need a service to prune the obsolete images.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-prune
spec:
  schedule: "0 3 * * *" # Schedule to run at 3 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prune
            image: docker:19.03.12
            command:
            - /bin/sh
            - -c
            - |
              docker system prune -af
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/os: linux
          tolerations:
          - key: "node-role.kubernetes.io/master"
            effect: "NoSchedule"

```
